### ISSUE TITLE
broken on Spigot 1.9

### ISSUE THREAD

**Issue by helptiger** [Acquized/Trashcan#1]
[13:11:29 WARN]: Exception in thread "Craft Scheduler Thread - 1604"
[13:11:29 WARN]: org.apache.commons.lang.UnhandledException: Plugin Trashcan v1.0 generated an exception while executing task 59653
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
at cc.acquized.trashcan.listeners.Drop$1.run(Drop.java:45)
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 3 more

**Comment by helptiger** [comment]
Rightclick also doesn't work

**Comment by Acquized** [comment]
Fixed, also thanks for your Pull Request that fixes this issue. A version on Spigot has been released.
